; Auto-generated by tools/gen-sprites.
; Do not edit by hand.

.chell_run_r1_x0_mask
    EQUB &FF,&EE,&CC,&CC,&CC,&CC,&CC,&88,&11,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&33,&33,&33,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&88,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&77,&FF,&FF,&77,&77,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&33,&77,&77,&77,&77,&77,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&CC,&CC,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &77,&77,&77,&FF,&FF,&77,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r1_x1_mask
    EQUB &FF,&FF,&EE,&EE,&EE,&EE,&EE,&CC,&88,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&77,&33,&11,&11,&11,&11,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &88,&88,&CC,&FF,&FF,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&33,&77,&77,&33,&33,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&FF,&FF,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&11,&11,&33,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&EE,&EE,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&33,&77,&77,&33,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r1_x2_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&EE,&CC,&88,&00,&00,&00,&00,&00,&00
    EQUB &77,&33,&11,&00,&00,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&77
    EQUB &CC,&CC,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&88,&88,&00,&00,&00
    EQUB &00,&11,&33,&33,&11,&11,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&88,&88,&00,&00,&00
    EQUB &00,&00,&00,&11,&11,&11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&11,&11,&33,&33,&11,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r1_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&EE,&CC,&88,&88,&88,&88,&88,&00
    EQUB &33,&11,&00,&00,&00,&00,&00,&00,&FF,&FF,&FF,&77,&77,&77,&77,&33
    EQUB &EE,&EE,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&CC,&CC,&88,&88,&88
    EQUB &00,&00,&11,&11,&00,&00,&00,&00,&77,&FF,&FF,&FF,&FF,&FF,&77,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&CC,&CC,&88,&88,&88
    EQUB &00,&00,&00,&00,&00,&00,&00,&00,&77,&77,&77,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&88,&88,&88,&88,&88
    EQUB &00,&00,&00,&11,&11,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&77,&77
.chell_run_r2_x0_mask
    EQUB &FF,&EE,&CC,&CC,&CC,&CC,&44,&00,&11,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&33,&33,&33,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&77,&FF,&FF,&77,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&33,&77,&33,&77,&77,&77,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&FF,&EE,&EE,&EE,&CC,&88,&CC,&00,&00,&00,&00,&44,&00,&00,&00
    EQUB &FF,&77,&77,&77,&FF,&77,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r2_x1_mask
    EQUB &FF,&FF,&EE,&EE,&EE,&EE,&AA,&88,&88,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&77,&33,&11,&11,&11,&11,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &88,&88,&EE,&FF,&FF,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&33,&77,&77,&33,&11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&11,&11,&33,&11,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&EE,&CC,&EE,&00,&88,&00,&00,&22,&00,&00,&00
    EQUB &77,&33,&33,&33,&77,&33,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r2_x2_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&DD,&CC,&CC,&88,&00,&00,&00,&00,&00,&00
    EQUB &77,&33,&11,&00,&00,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&77
    EQUB &CC,&CC,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&88,&88,&00,&00,&00
    EQUB &00,&11,&33,&33,&11,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&88,&88,&88,&88,&88
    EQUB &00,&00,&00,&11,&00,&11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&EE,&FF,&88,&CC,&88,&88,&99,&00,&00,&00
    EQUB &33,&11,&11,&11,&33,&11,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r2_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&EE,&EE,&EE,&CC,&88,&88,&88,&88,&88,&00
    EQUB &33,&11,&00,&00,&00,&00,&00,&00,&FF,&FF,&FF,&77,&77,&77,&77,&33
    EQUB &EE,&EE,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&88,&CC,&CC,&88,&88,&88
    EQUB &00,&00,&11,&11,&00,&00,&00,&00,&77,&FF,&FF,&FF,&FF,&77,&77,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&CC,&CC,&CC,&CC,&CC
    EQUB &00,&00,&00,&00,&00,&00,&00,&00,&77,&77,&77,&FF,&77,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&CC,&EE,&CC,&CC,&CC,&88,&00,&88
    EQUB &11,&00,&00,&00,&99,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&77,&77
.chell_run_r3_x0_mask
    EQUB &FF,&FF,&EE,&CC,&CC,&CC,&44,&00,&FF,&11,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&FF,&77,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&CC,&CC,&EE,&EE,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&33,&77,&FF,&FF,&77,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&CC,&EE,&EE,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&33,&33,&77,&33,&77,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&CC,&CC,&CC,&88,&88,&00,&00,&00,&00,&00,&66,&66,&22
    EQUB &33,&33,&33,&33,&33,&33,&11,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_run_r3_x1_mask
    EQUB &FF,&FF,&FF,&EE,&EE,&EE,&AA,&88,&FF,&88,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&11,&11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &88,&88,&EE,&EE,&FF,&FF,&EE,&EE,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &00,&11,&33,&77,&77,&33,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&EE,&FF,&FF,&FF,&FF,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &11,&11,&11,&11,&33,&11,&33,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&EE,&EE,&EE,&CC,&CC,&00,&00,&00,&00,&00,&33,&33,&11
    EQUB &11,&11,&11,&11,&11,&11,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&77
.chell_run_r3_x2_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&DD,&CC,&FF,&CC,&88,&00,&00,&00,&00,&00
    EQUB &FF,&77,&33,&11,&00,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&00,&88,&88,&00,&00
    EQUB &00,&00,&11,&33,&33,&11,&00,&00,&77,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&00,&88,&88,&88,&88
    EQUB &00,&00,&00,&00,&11,&00,&11,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&EE,&EE,&88,&88,&88,&00,&00,&11,&11,&00
    EQUB &00,&00,&00,&00,&00,&88,&88,&88,&FF,&FF,&FF,&FF,&FF,&FF,&77,&33
.chell_run_r3_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&EE,&EE,&FF,&EE,&CC,&88,&88,&88,&88,&00
    EQUB &FF,&33,&11,&00,&00,&00,&00,&00,&FF,&FF,&FF,&FF,&77,&77,&77,&77
    EQUB &EE,&EE,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&88,&88,&CC,&CC,&88,&88
    EQUB &00,&00,&00,&11,&11,&00,&00,&00,&33,&77,&FF,&FF,&FF,&FF,&77,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&88,&CC,&CC,&CC,&CC
    EQUB &00,&00,&00,&00,&00,&00,&00,&00,&77,&77,&77,&77,&FF,&77,&FF,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&CC,&CC,&CC,&88,&88,&88,&00,&00
    EQUB &00,&00,&00,&00,&00,&CC,&CC,&44,&77,&77,&77,&77,&77,&77,&33,&11
.chell_rgun_r1_x0_mask
    EQUB &FF,&EE,&CC,&CC,&CC,&CC,&CC,&88,&11,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&88,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&77,&FF,&FF,&77,&77,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &00,&00,&33,&77,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&CC,&CC,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&77,&77,&FF,&77,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r1_x1_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&CC,&CC,&CC,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&77,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r1_x2_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&EE,&EE,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&33,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&77,&77
    EQUB &EE,&EE,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&11,&FF,&FF,&FF,&FF,&FF,&77,&77,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r1_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&11,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&33,&33
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&00,&FF,&FF,&FF,&FF,&FF,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r1_x4_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88
    EQUB &FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&11,&11
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&00,&FF,&FF,&FF,&FF,&FF,&11,&11,&77,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r2_x0_mask
    EQUB &FF,&EE,&CC,&CC,&CC,&CC,&44,&00,&11,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&77,&FF,&FF,&77,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&11,&00,&00,&00,&22,&33,&FF,&FF,&FF,&FF,&77,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&CC,&EE,&CC,&88,&CC,&00,&44,&44,&44,&44,&00,&00,&00
    EQUB &33,&33,&77,&77,&FF,&33,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r2_x1_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&CC,&CC,&CC,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&CC,&CC,&FF,&00,&00,&00,&00,&00,&00,&00,&FF
    EQUB &33,&33,&11,&00,&00,&00,&22,&FF,&FF,&FF,&FF,&FF,&77,&FF,&FF,&FF
.chell_rgun_r2_x2_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&EE,&EE,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &EE,&EE,&EE,&FF,&FF,&EE,&EE,&FF,&00,&00,&00,&00,&00,&00,&00,&FF
    EQUB &11,&11,&00,&00,&00,&00,&11,&FF,&FF,&FF,&FF,&77,&33,&77,&77,&FF
.chell_rgun_r2_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00
    EQUB &FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&88,&88,&00,&00,&FF
    EQUB &00,&00,&00,&00,&00,&00,&00,&FF,&FF,&FF,&77,&33,&11,&33,&BB,&FF
.chell_rgun_r2_x4_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88
    EQUB &FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&77,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&CC,&CC,&88,&88,&FF
    EQUB &00,&00,&00,&00,&00,&00,&00,&FF,&77,&77,&33,&11,&00,&11,&55,&FF
.chell_rgun_r3_x0_mask
    EQUB &FF,&EE,&CC,&CC,&CC,&44,&00,&00,&11,&00,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&33,&33,&33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&CC,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&77,&EE,&CC,&00,&00,&11,&33,&FF,&FF,&FF,&FF,&FF,&77,&FF,&FF
    EQUB &CC,&CC,&CC,&EE,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &33,&33,&33,&77,&33,&77,&77,&77,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&CC,&EE,&CC,&CC,&CC,&00,&00,&00,&00,&00,&00,&00,&00
    EQUB &77,&33,&33,&33,&77,&33,&11,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r3_x1_mask
    EQUB &FF,&FF,&CC,&EE,&EE,&CC,&CC,&CC,&FF,&FF,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&EE,&CC,&00,&00,&11,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
    EQUB &CC,&CC,&CC,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &33,&33,&33,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r3_x2_mask
    EQUB &FF,&FF,&EE,&FF,&FF,&EE,&EE,&EE,&FF,&FF,&00,&00,&00,&00,&00,&00
    EQUB &FF,&FF,&77,&66,&00,&00,&00,&11,&FF,&FF,&77,&77,&77,&77,&FF,&FF
    EQUB &EE,&EE,&EE,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &11,&11,&11,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r3_x3_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&88,&88,&00,&00,&00
    EQUB &FF,&FF,&33,&33,&00,&00,&00,&00,&FF,&FF,&BB,&33,&33,&33,&77,&FF
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&00,&00,&00,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&00,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF
.chell_rgun_r3_x4_mask
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&CC,&CC,&88,&88,&88
    EQUB &FF,&FF,&11,&11,&00,&00,&00,&00,&FF,&FF,&DD,&99,&11,&11,&33,&77
    EQUB &FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&88,&88,&88,&FF,&FF,&FF,&FF,&FF
    EQUB &00,&00,&00,&FF,&FF,&FF,&FF,&FF,&77,&77,&77,&FF,&FF,&FF,&FF,&FF
